### ISSUE TITLE
Run dot with docker

### ISSUE THREAD

**Issue by giorgiop** [sensity-ai/dot#10]

**Comment by AjinkyaIndulkar** [comment]
issue might be linked to #5.

**Comment by vid** [comment]
OK but where's the Dockerfile?

**Comment by governor97** [comment]
Are you lost?

**Comment by vid** [comment]
Maybe, me and the Dockerfile.

**Comment by governor97** [comment]
You need cash?

**Comment by vid** [comment]
If I did, there would be an issue for that. But there's just #10 and #5.
