### ISSUE TITLE
Select target in GUI, which one?

### ISSUE THREAD

**Issue by OnlyStopOnTop** [sensity-ai/dot#100]
I have the DOT.exe and working with the GUI.
I watched the short video to set up the GUI, but can´t find out which number I should pick to get my camera run?

I tried the numbers: 1,2,3,4 and 5

Everytime the console says: "Camera X does not exist"

Also what does gpen_256 and gpen_512 mean?

Best regards

**Comment by Ghassen-Chaabouni** [comment]
Did you try 0 for the target? 
gpen is a Face Restoration model https://github.com/yangxy/GPEN. We use it to improve the result of SimSwap. There are 2 models one with resolution 256 and the other with resolution 512. You can try both and select the one that works best in your case.

**Comment by OnlyStopOnTop** [comment]
0 worked fine for me. thanks!
