### ISSUE TITLE
 WinError 6 The handle is invalid question error

### ISSUE THREAD

**Issue by fiziko** [sensity-ai/dot#112]
## :bug: Bug Report

 WinError 6 The handle is invalid question error i cant see in where give this error.

### Description:

i am use latest version dot.exe binary downloaded from this link https://drive.google.com/file/d/10fdnSszaEbpGdCKxxeBFXQrkagxe3-RT/view?pli=1

i am update this models manually too https://drive.google.com/u/0/uc?id=1Qaf9hE62XSvgmxR43dfiwEPWWS_dXSCE&export=download

still getting error with simswap

**Comment by Ghassen-Chaabouni** [comment]
Can you share more about the system you are running this on?

**Comment by fiziko** [comment]
Hello cuda 12 windows 11 3080 ti gpu i7 13x

**Comment by giorgiop** [comment]
duplicate of https://github.com/sensity-ai/dot/issues/109
