### ISSUE TITLE
DOT is using only CPU

### ISSUE THREAD

**Issue by eremia01** [sensity-ai/dot#113]

**Comment by Ghassen-Chaabouni** [comment]
What's the error message that you are getting when running dot on gpu?

**Comment by QRage** [comment]
In my case I'm getting first line in console after enter GPU run command:
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.

That may confuse. But by run with only CPU you can see the differences. 
*spoiler* should get less FPS.

**Comment by giorgiop** [comment]
> In my case I'm getting first line in console after enter GPU run command:
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.

This is not an issue, as it's a warning thrown by `mediapipe`. dot will run on GPU if one is available

**Comment by Ghassen-Chaabouni** [comment]
To double check if `dot` is using CPU or GPU, you can run dot with and without `--use_gpu`. You should notice a difference in the speed.
Also, you can check `nvidia-smi` when `dot` is running

**Comment by giorgiop** [comment]
close due to inactivity
