### ISSUE TITLE
Does it possible to improve the quality of face swap in a photo?

### ISSUE THREAD

**Issue by QRage** [sensity-ai/dot#124]
Is there any way to improve quality of face swap?
<details>
  <summary>Screenshot result</summary>
  <img src=https://i.imgur.com/w2irMEm.jpg >
</details>

Used command from Colab examples:
<details>
  <summary>Command</summary>
  dot 
-c ./configs/simswap.yaml 
--target "data/" 
--source "data/" 
--save_folder "image_simswap_output/" 
--use_image 
--use_gpu
</details>

**Comment by giorgiop** [comment]
Hi @QRage , have you tried the other options of `simswapHQ` and `gpen` ?

https://github.com/sensity-ai/dot#cli-usage

**Comment by QRage** [comment]
Thank you, @giorgiop for advice! Have not try it yet.
Need to check it.

**Comment by giorgiop** [comment]
@QRage did it work as expected? can we close?

**Comment by QRage** [comment]
Yes, those parameters works for me. Thanks.
