### ISSUE TITLE
CLI & GUI INSTALLATION NOT WORKING "FOR CLI: CANT CREATE VIRTUAL ENVIRONMENT"

### ISSUE THREAD

**Issue by PIA89120** [sensity-ai/dot#126]
### Description:

I installed the package, extracted it then pressed DOT cmd and it would just stay there doing nothing so i Assumed it didnt work.
I went ahead and the did CLI installation and installed all the packages. When i get to the part where you start the environment,

" EnvironmentFileNotFound: 'C:\WINDOWS\system32\envs\environment-gpu.yaml' file not found " - When typing the command
conda env create -f envs/environment-gpu.yaml to start the virtual environment.

---> I originally instead 11.8 CUDA, the toolkit, torch and torchvision as requested, but it did not work.

SO Both installations seem to not be working for me. if you could help me out I would greatly appreciate it.

**Comment by Ghassen-Chaabouni** [comment]
Can you send me information about you OS

> I installed the package, extracted it then pressed DOT cmd and it would just stay there doing nothing so i Assumed it didnt work.

Are there any logs? Can you send a screenshot of the cmd.  (By the way, don't click on the cmd when you run `dot` because you will pause the process if you are on windows)

> I went ahead and the did CLI installation and installed all the packages. When i get to the part where you start the environment,
> 
> " EnvironmentFileNotFound: 'C:\WINDOWS\system32\envs\environment-gpu.yaml' file not found " - When typing the command
> conda env create -f envs/environment-gpu.yaml to start the virtual environment.

You should `cd` to the path of `dot` before creating the environment (`cd path/to/dot`)

**Comment by PIA89120** [comment]
Got it working, but im asking another Q, just check
