### ISSUE TITLE
Great job! Imagine if you could swap your race.

### ISSUE THREAD

**Issue by RFARREY** [sensity-ai/dot#131]
Imagine if you could swap your race. Let's examine this scenario. An African American has swapped the face of a white or Asian male. The downside is, that you can have a neat face swap where all required gestures to pass a verification are on point but then the neck is that of a black male or if they are required to show a hand gesture, it won't pass because their skin color will be different from the swapped face. Can you include a module that can swap skin color, even when the subject vying for verification is required to make a hand gesture in the dynamic I have just described? Think along the lines of inpainting a skin color and using pre-trained controllnet models to arbitrarily select pre-trained gestures that can be used to perform gesture verification if required [This idea , I think can be used to resolve the 'skin color inpainting' idea I just described ]

**Comment by giorgiop** [comment]
this is out of scope for dot.
