### ISSUE TITLE
Is there any way to use GPU at 100%? (laptop rtx 3080)

### ISSUE THREAD

**Issue by Daizzeren** [sensity-ai/dot#145]
### Description: 
Hello. I would like to send my thanks to the developer of this software. 

The app works well and the quality of the DF is quite high. However, my GPU rtx 3080ti (laptop) is putting out about 8fps (simswap + 256_gpen) at 30-40% load. I understand that you have optimized the application to work with all hardware, but is there any way (maybe make changes to the code) to unlock the full potential of the GPU?

**Comment by Ghassen-Chaabouni** [comment]
Currently, we don't have plans to work on this feature. However, feel free to contribute to the repo. A suggestion is to move all of the operations in this script [reverse2original.py](https://github.com/sensity-ai/dot/blob/main/src/dot/simswap/util/reverse2original.py) to GPU. Some were kept on CPU to reduce the GPU usage

**Comment by Daizzeren** [comment]
@Ghassen-Chaabouni Thank you!
