### ISSUE TITLE
Video swap with GPEN option

### ISSUE THREAD

**Issue by epicstar7** [sensity-ai/dot#15]
Is there any working way to perform a faceswap on a video with the GPEN option using dot right now?

**Comment by epicstar7** [comment]
Managed to get it working with the --use_video option. Maybe good to add this to the readme.

**Comment by giorgiop** [comment]
> Managed to get it working with the --use_video option. Maybe good to add this to the readme.

@epicstar7 PRs are welcome!

**Comment by ghassen1302** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(2) Add dot logo](https://trello.com/c/pzVEBiQK/3082-2-add-dot-logo)
