### ISSUE TITLE
How can I use my AMD GPU for DOT?

### ISSUE THREAD

**Issue by TheSiker** [sensity-ai/dot#152]
Hi, I wonder if I am able to use utilize my amd gpu instead of going full cpu on my computer.
If so, what do I need to do?

**Comment by TheSiker** [comment]
Forgot to add gpu. It is an RX 580 series GPU that I use

**Comment by giorgiop** [comment]
Sorry, we only support NVIDIA GPU at the moment! PR for this are welcome!
