### ISSUE TITLE
Dot not swapping image files

### ISSUE THREAD

**Issue by TheSiker** [sensity-ai/dot#153]
Hey, I need help for swapping image files on DOT.
I use Windows 11 for DOT

**Comment by Ghassen-Chaabouni** [comment]
For now swapping images arent supported in the GUI. They are supported in the CLI 
https://github.com/sensity-ai/dot?tab=readme-ov-file#run-dot-on-pre-recorded-image-and-video-files

**Comment by Ghassen-Chaabouni** [comment]
Swapping images and videos were added to the GUI after this PR https://github.com/sensity-ai/dot/pull/116
