### ISSUE TITLE
Did you include a watermark in DOT?

### ISSUE THREAD

**Issue by a-t-0** [sensity-ai/dot#24]
### Description:

For the DOT to work reliably independent of whether or not an authenticator used the/a watermark detector, it is important the DOT is indistinguishable from an arbitrary real stream. Hence, I was wondering whether you included a watermark or not. Additionally, I would like to kindly ask: would you perhaps be able to enlighten us on whether there are data characteristics/signatures that hint on the DOT being used instead of an arbitrary video?

**Comment by giorgiop** [comment]
No watermark is included at the moment.
