### ISSUE TITLE
How to enable super resolution

### ISSUE THREAD

**Issue by ak3389** [sensity-ai/dot#35]
dot \
-c ./configs/simswap.yaml \
--target 0 \
--source "./data" \
--show_fps \
--gpen_type gpen_256

I used this command, but my GUP doesn't seem to be working and the video is very stuttering. I use a 2060 12G graphics card

**Comment by ghassen1302** [comment]
@ak3389 You are using only the CPU. Add the option `--use_gpu` to use the GPU.
