### ISSUE TITLE
Does this only work with camera footage or can a video be imported? 

### ISSUE THREAD

**Issue by fuzzyfazzy** [sensity-ai/dot#38]

**Comment by ghassen1302** [comment]
For using `dot` with a video, check here [faceswap-on-video-files](https://github.com/sensity-ai/dot/blob/main/docs/run_without_camera.md#faceswap-on-video-files-simswap)

**Comment by giorgiop** [comment]
Additionally, you can use dot on Colab https://colab.research.google.com/github/sensity-ai/dot/blob/main/notebooks/colab_demo.ipynb

**Comment by fuzzyfazzy** [comment]
Thanks all!
