### ISSUE TITLE
How to set DOT on windows?

### ISSUE THREAD

**Issue by Greytso** [sensity-ai/dot#44]
I can’t figure out the installation, there are no options for installing on windows in the documentation, although the instructions for installing on windows are written only for Obs studio. please give advice.

**Comment by Ghassen-Chaabouni** [comment]
@Greytso Please follow the instructions under [installation](https://github.com/sensity-ai/dot#installation). If there is no mention to windows, then there is no additional step needed for it. They are common instructions that should work for all OS types
