### ISSUE TITLE
Run dot on cloud GPU

### ISSUE THREAD

**Issue by giorgiop** [sensity-ai/dot#5]
For users without an available local GPU, we should support cloud GPU compute.

See: 
https://github.com/cmusatyalab/openrtist
https://github.com/alievk/avatarify-python#news

**Comment by OnlyStopOnTop** [comment]
is a ipgu not enough? like intel iris xe or ryzen zen 3?

**Comment by OnlyStopOnTop** [comment]
is it possible to run on cloud gpu now?

**Comment by giorgiop** [comment]
we won't support this
