### ISSUE TITLE
During the dot installation phase, an error appears 

### ISSUE THREAD

**Issue by skoorpion963** [sensity-ai/dot#50]
I get an error when I follow the instructions, tell me what's wrong 

### Install dot

```bash
pip install -e .
```

(dot) C:\Users\Александр>pip install -e .

Obtaining file:///C:/Users/%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80
ERROR: file:///C:/Users/%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80 does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

**Comment by Ghassen-Chaabouni** [comment]
You are running `pip install -e .` from the path `C:\Users\Александр`
Please `cd` into the `dot` project before running it.
```
cd path/to/dot
pip install -e .
```
