### ISSUE TITLE
Error no Face detected!

### ISSUE THREAD

**Issue by Shimoli** [sensity-ai/dot#58]
When I run on cpu i got the following errors an I followed everything correctly:
'strict' is an invalid keyword argument for load()
=== Control keys ===
1-9: Change avatar
1: .\data\ronaldo.png
2: .\data\schwarzenegger.png
3: .\data\Brad Pitt.jpg
4: .\data\David Beckham.jpg
5: .\data\einstein.jpg
6: .\data\eminem.jpg
7: .\data\jobs.jpg
8: .\data\Joe Biden.jpg
9: .\data\Leonardo Dicaprio.jpg
10: .\data\Markiplier.jpg
11: .\data\mona.jpg
12: .\data\obama.jpg
13: .\data\Pewdiepie.jpg
14: .\data\potter.jpg
15: .\data\Tom Cruise.jpg
C:\Users\Pro\miniconda3\envs\dot\lib\site-packages\torch\nn\functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ..\c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
C:\Users\Pro\miniconda3\envs\dot\lib\site-packages\torch\nn\functional.py:3609: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  warnings.warn(
ERROR: No face detected!
ERROR: No face detected!
ERROR: No face detected!
ERROR: No face detected!

Aborted!

**Comment by Ghassen-Chaabouni** [comment]
@Shimoli The error `No face detected!` indicates that there is no face visible. Make sure that you are using the correct `--target` for your webcam and your face is visible.

**Comment by Shimoli** [comment]
I figured it but the image on webcam was doing nothing, does it mean I should wait for the software to process the image conversion? I am using cpu pc no gpu.

**Comment by Ghassen-Chaabouni** [comment]
> I figured it but the image on webcam was doing nothing, does it mean I should wait for the software to process the image conversion? I am using cpu pc no gpu.

Yes, you need to wait. It's not recommended to use `dot` with CPU and webcam because it's slow. You can try [run_without_camera](https://github.com/sensity-ai/dot/blob/main/docs/run_without_camera.md) instead.
