### ISSUE TITLE
ERROR: Package 'dot' requires a different Python: 3.10.8 not in '<3.9,>=3.8'

### ISSUE THREAD

**Issue by OnlyStopOnTop** [sensity-ai/dot#63]
## :bug: Bug Report

Python downgrade?

### Description:

Python 3.10.8 latest miniconda installed. Do I need a downgrade? if yes to which version exactly?

**Comment by dzhenway** [comment]
In my case, I have to downgrade the Python version from 3.9.x to 3.8.6

**Comment by AjinkyaIndulkar** [comment]
Please follow the install instructions mentioned here: https://github.com/sensity-ai/dot#create-conda-environment

We recommend using a virtual environment to easily manage `dot` dependencies and also avoid any command name clashes (Related: https://github.com/sensity-ai/dot/issues/11)

**Comment by OnlyStopOnTop** [comment]
I did but for now I got several problems installing dot, is there any support for the install guide?

**Comment by AjinkyaIndulkar** [comment]
can you please share the error log? At the moment, I am unable to understand the root cause of the installation errors.
