### ISSUE TITLE
There is no "[python.exe]: fomm" in Windows dropdown

### ISSUE THREAD

**Issue by Shimoli** [sensity-ai/dot#65]
Following the guide on here [https://github.com/sensity-ai/dot#virtual-camera-injection](url) I can't find [python.exe]: fomm, I am using OBS 27.0.1 as you describe because the current version of OBS has built in virtual camera, there is no something like "[python.exe]: fomm" as you described here. (In the appeared window, choose "[python.exe]: fomm" in Window drop-down menu and press OK.) Also there is no In OBS Studio, go to Tools -> VirtualCam. Check AutoStart section on OBS What am i missing, what version of the OBS does this dot works with?

**Comment by dzhenway** [comment]
I'm using OBS 29.0.2 and found `[python.exe]: cam` not `[python.exe]: fomm` and worked like charm

**Comment by Shimoli** [comment]
Even it does not show [python.exe]: do i need to open python or install python where in my laptop.

**Comment by Shimoli** [comment]
I figured
