### ISSUE TITLE
EnvironmentFileNotFound: 'C:\Users\envs\environment-cpu.yaml' file not found

### ISSUE THREAD

**Issue by OnlyStopOnTop** [sensity-ai/dot#68]
By entering the conda env create -f envs/environment-gpu.yaml at the frist step.

What am I doing wrong? I open anaconda prompt and enter the code.

Best regards

**Comment by OnlyStopOnTop** [comment]
<img width="385" alt="Screenshot 2023-02-16 213142" src="https://user-images.githubusercontent.com/124540269/219480302-c9d55c5b-2bd3-43e6-a3eb-efb9638d2285.png">

**Comment by AjinkyaIndulkar** [comment]
The working directory on the terminal needs to be the folder where you have cloned the repository. The path `envs/environment-gpu.yaml` is relative to the repository folder path.
