### ISSUE TITLE
Can Dot work good on a laptop core5 with Nvidia GTX 750?

### ISSUE THREAD

**Issue by Shimoli** [sensity-ai/dot#69]
I don't have money to buy an expensive laptop I tried dot on a normal laptop with CPU alone it was super slow with lagging image head rotation. My question is Can Dot work good on a laptop core5 with Nvidia GTX 750?

**Comment by AjinkyaIndulkar** [comment]
We don't recommend using `dot` on CPU as there are some models which require GPU to run faster.

We haven't benchmarked on GTX 750 graphics card but it should work. You can check our speed benchmarks here: https://github.com/sensity-ai/dot#speed
