### ISSUE TITLE
How to run dot?

### ISSUE THREAD

**Issue by OnlyStopOnTop** [sensity-ai/dot#71]
Ask a Question:

Did everything as described. But zoom/obs is not showing anything, only a black screen of obs and my mouse movements.

How to I set it up to use the facecam?

**Comment by giorgiop** [comment]
Hi, please describe what OS you are using, and what instructions you followed exactly

**Comment by OnlyStopOnTop** [comment]
Hello,

I use Win11 OS.

I did everything as described, the last step looks like this:
<img width="350" alt="dot status" src="https://user-images.githubusercontent.com/124540269/220207017-21c5b494-23a9-42fb-b605-de93db0eb582.png">

Opening Zoom and selecting OBS virtual camera is not showing anything (i did every step to install virtual cam+obs).

**Comment by Ghassen-Chaabouni** [comment]
@OnlyStopOnTop Did you keep `dot` running `dot -c ./configs/simswap.yaml --target 0 --source "./data" --use_gpu`
and then selected the python window in `OBS` `Windows Capture` as described in the second point [here](https://github.com/sensity-ai/dot#windows) ?

**Comment by OnlyStopOnTop** [comment]
Dot running screen (i use cpu, only have igpu):

<img width="806" alt="condaactivate" src="https://user-images.githubusercontent.com/124540269/220651466-7da75e34-8ddf-4195-ad0b-0bfbf09322fa.png">

OBS Screen:

![obs screeen](https://user-images.githubusercontent.com/124540269/220651515-53f38e7a-c796-4b46-8c1d-ac75a4398c8f.png)

**Comment by OnlyStopOnTop** [comment]
if it´s possible we can connect though teamviewer and I would appreciate if someone would guide me through the right installation.
Of course I´m open for a donation after that.

**Comment by OnlyStopOnTop** [comment]
up!

**Comment by OnlyStopOnTop** [comment]
up!

**Comment by Ghassen-Chaabouni** [comment]
> Dot running screen (i use cpu, only have igpu):
> 
> <img alt="condaactivate" width="806" src="https://user-images.githubusercontent.com/124540269/220651466-7da75e34-8ddf-4195-ad0b-0bfbf09322fa.png">

I think that you are missing the models. Check the instructions under [download-models](https://github.com/sensity-ai/dot#download-models) . You need to have the models under the folder `saved_models`

**Comment by OnlyStopOnTop** [comment]
Ok it´s working! The problem was that the saved_models were in an extra folder and i had to remove it.
As expected, running dot with CPU power is not recommended due to low performance.
