### ISSUE TITLE
How can I convert it into exe?

### ISSUE THREAD

**Issue by Gamemg** [sensity-ai/dot#76]
Hi
how can I convert dot fully with all of its library into exe?
I tried a few things it didn't work out for me.
Could anyone please guide me properly which things to use or anything else?

Thank You

**Comment by Ghassen-Chaabouni** [comment]
This was mentioned in this issue https://github.com/sensity-ai/dot/issues/70.

> We don't support it yet. We'd welcome community contributions working on it!

**Comment by Gamemg** [comment]
But can you guide atleast little bit which path I should go?

**Comment by labellson** [comment]
@Gamemg you could try with https://pyinstaller.org/en/stable/

**Comment by Ghassen-Chaabouni** [comment]
@Gamemg I generated the exe in this draft https://github.com/sensity-ai/dot/pull/92. Can you confirm if it's working for you?
