### ISSUE TITLE
ImportError: Failed to load DLL while importing _dlib_pybind11: The specified module was not found

### ISSUE THREAD

**Issue by OnlyStopOnTop** [sensity-ai/dot#84]
Uninstalled and installed dlib 19.24.2

I get the error by using dot. Setting up dot was succesfull.

CUDA 11.7

Need help.

**Comment by Ghassen-Chaabouni** [comment]
@OnlyStopOnTop I generated an exe of dot in this draft https://github.com/sensity-ai/dot/pull/92. Can you confirm if it's working for you?
