### ISSUE TITLE
Apple M1/M2 Compatibility 

### ISSUE THREAD

**Issue by vassilispapadop** [sensity-ai/dot#86]
### Description:
Make DOT compatible with Apple Silicon(M1, M2)

Review and update any dependencies/libraries that may not be compatible with the Apple Silicon.

**Comment by mrwhitely** [comment]
any updates on getting this working on Apple silicon? CPU is too slow to use it properly and CUDA is for nvidia GPUs, so Apple users are a bit stuck. Would be great if so!
