### ISSUE TITLE
The deepfake output didn't show up on Genymotion

### ISSUE THREAD

**Issue by Wayc0des-Land** [sensity-ai/dot#91]
### Description:

Genymotion: 3.2.1
Cam: e2eSoft VCam & OBS-Camera (Virtual Camera Injection)

Hi @Ghassen-Chaabouni & @giorgiop 

Both e2eSoft VCam and OBS-Camera were employed as part of the setup to facilitate the generation and virtualization of the deepfake output. However, upon inspection, it was observed that the expected output did not appear within the Genymotion environment. any ideas?

this is a sample output for OBS-Camera and my configuration for virtual cam
![image](https://github.com/sensity-ai/dot/assets/49187195/2e82d3c8-cafc-45ab-877b-55b5b6bb428e)
![image](https://github.com/sensity-ai/dot/assets/49187195/11cd79c9-25a2-4946-b8cd-4bc1057f6868)

**Comment by Ghassen-Chaabouni** [comment]
Are you running OBS and are you seeing the output of dot in OBS?

**Comment by Wayc0des-Land** [comment]
Yes, I am running OBS, and I am able to see the output of "dot" within OBS.
| Are you running OBS and are you seeing the output of dot in OBS?

Yes, the vcam is set up correctly in OBS. I can confirm this because I have a new submenu called "Virtual Cam" in the "Tools" menu.
| Also is the vcam set up correctly in OBS?

**Comment by Wayc0des-Land** [comment]
hi @Ghassen-Chaabouni 

Would it be possible for us to have a quick call? Maybe via Discord

**Comment by Ghassen-Chaabouni** [comment]
> hi @Ghassen-Chaabouni
> 
> Would it be possible for us to have a quick call? Maybe via Discord

Sure, let's have a call with Google Meet. Please send me the meeting invite to my email: [ghassen1302@live.com](mailto:ghassen1302@live.com)

**Comment by Ghassen-Chaabouni** [comment]
@Wayc0des-Land You can try with manycam. It worked also when I tested it

**Comment by Wayc0des-Land** [comment]
> > hi @Ghassen-Chaabouni
> > Would it be possible for us to have a quick call? Maybe via Discord
> 
> Sure, let's have a call with Google Meet. Please send me the meeting invite to my email: [ghassen1302@live.com](mailto:ghassen1302@live.com)

send it.

**Comment by Ghassen-Chaabouni** [comment]
I'm joining

**Comment by Wayc0des-Land** [comment]
solved! thanks, @Ghassen-Chaabouni

**Comment by Wayc0des-Land** [comment]
> Solution: OBS was not working properly with Genymotion. We ended up using ManyCam with the emulator.

Perhaps you can add or update that information in the README.md

thanks man
